S3_FILE_URL_PATH = "https://s3-%s.amazonaws.com/%s/%s"
BASE_VERSION_STR = "1.0.0"
VERSION_JSON_PATH = "alpha/media/retool-app-jsons/version.json"
BASE_JSONS_PKG_PATH = "old_jsons"
BASE_ENV_CONFIG_PATH = "config_jsons/old_env_config.json"
